#!/bin/bash
# u1sdtool wrapper for headless Ubuntu One
echo "running headless"
eval $(ps xe | gawk '/[u]buntuone-syncdaemon/ { \
    match($0, "DBUS_SESSION_BUS_ADDRESS=([^ ]*)", a); \
    print a[0]}')

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    # Ubuntu One is not running and we don't have a dbus daemon
    DBUS_SESSION_BUS_ADDRESS=`dbus-daemon --session  --print-address --fork`
fi

export DBUS_SESSION_BUS_ADDRESS


python /home/jono/validation-service/sharecheck.py
